### ISSUE TITLE
Edit tab is too large

### ISSUE THREAD

**Issue by diegoiast** [shemeshg/pass-simple-qt#11]
If you look - the first tab of the tab image is always a little bigger than it should be. I am unsure why, nor how to fix it.

![image](https://user-images.githubusercontent.com/21070/223210256-c382bf54-b7d0-49d1-98a0-a2dba1c173d7.png)

**Comment by shemeshg** [comment]
I can confirm it occurs on macos too.
I'll try to reproduce that in a new empty project, 

It is actually the same height with the others. 
The only difference is a 1px bar bellow the "Edit" button (Might be some kind of a padding.

If issue is reproducible and a bug, I can post that on the 'Qt Forum' too.

**Comment by shemeshg** [comment]
It is Qt issue, reproducible with the example they have on site

https://doc.qt.io/qt-6/qml-qtquick-controls2-tabbar.html

![Screen Shot 2023-03-12 at 5 53 50 PM](https://user-images.githubusercontent.com/8200598/224556696-54acee76-0214-4471-82d8-6a6f8ea46415.png)

I've opened a Qt forum ticket for that 

https://forum.qt.io/topic/143580/tabbar-issue-first-button-has-transparent-line-below-it

```qml
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

//https://doc.qt.io/qt-6/qml-qtquick-controls2-tabbar.html
ApplicationWindow {
    width: 640
    height: 480
    visible: true
    title: qsTr("Hello World")
    ColumnLayout {
        Layout.fillWidth: true
        width: parent.width

        TabBar {
            id: bar
            width: parent.width
            TabButton {
                text: qsTr("Home")
            }
            TabButton {
                text: qsTr("Discover")
            }
            TabButton {
                text: qsTr("Activity")
            }
        }

        StackLayout {
            width: parent.width
            currentIndex: bar.currentIndex
            Item {
                id: homeTab
            }
            Item {
                id: discoverTab
            }
            Item {
                id: activityTab
            }
        }

    }
}

```
