### ISSUE TITLE
Inconsistant icons

### ISSUE THREAD

**Issue by diegoiast** [shemeshg/pass-simple-qt#12]
Each icon looks different. I found the online site you used for existing icons... but trying to match all actions is a pain. You can find "file new" - and then matching a "folder upload icon" is purposely impossible. I tried looking into icon packs... and IMHO, Android material icons looks similar to what you were looking for.

https://fonts.google.com/icons?icon.query=folder

**Comment by shemeshg** [comment]
I can try use the `google icons`. thanks.

**Comment by diegoiast** [comment]
or at least create a coherent icon set from icon8 (and in such case - it needs to be added to the about box).

**Comment by shemeshg** [comment]
Closed by:

https://github.com/shemeshg/pass-simple-mdbook/pull/1

https://github.com/shemeshg/pass-simple-qt/pull/14
