### ISSUE TITLE
Indentation is ... not optimal

### ISSUE THREAD

**Issue by diegoiast** [shemeshg/pass-simple-qt#2]
The indentation of the code is not optimal. We can have a clang-format definition and enforce it.

**Comment by shemeshg** [comment]
Closed by #3

**Comment by shemeshg** [comment]
Thanks, 

Should I remember to run `run-clang-tidy` manually every change?
With what parameters would you recommand?

Thanks
Shemeshg

**Comment by shemeshg** [comment]
OK I see: in the documentation

https://github.com/TheLartians/Format.cmake

Thanks
